//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace storeManager.Entities
{
    public partial class StoreManagerDBEntities : ObjectContext
    {
        public const string ConnectionString = "name=StoreManagerDBEntities";
        public const string ContainerName = "StoreManagerDBEntities";
    
        #region Constructors
    
        public StoreManagerDBEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public StoreManagerDBEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public StoreManagerDBEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Address> Addresses
        {
            get { return _addresses  ?? (_addresses = CreateObjectSet<Address>("Addresses")); }
        }
        private ObjectSet<Address> _addresses;
    
        public ObjectSet<AddressType> AddressTypes
        {
            get { return _addressTypes  ?? (_addressTypes = CreateObjectSet<AddressType>("AddressTypes")); }
        }
        private ObjectSet<AddressType> _addressTypes;
    
        public ObjectSet<Brand> Brands
        {
            get { return _brands  ?? (_brands = CreateObjectSet<Brand>("Brands")); }
        }
        private ObjectSet<Brand> _brands;
    
        public ObjectSet<Category> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Category>("Categories")); }
        }
        private ObjectSet<Category> _categories;
    
        public ObjectSet<Company> Companies
        {
            get { return _companies  ?? (_companies = CreateObjectSet<Company>("Companies")); }
        }
        private ObjectSet<Company> _companies;
    
        public ObjectSet<Country> Countries
        {
            get { return _countries  ?? (_countries = CreateObjectSet<Country>("Countries")); }
        }
        private ObjectSet<Country> _countries;
    
        public ObjectSet<Customer> Customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<Customer>("Customers")); }
        }
        private ObjectSet<Customer> _customers;
    
        public ObjectSet<Employee> Employees
        {
            get { return _employees  ?? (_employees = CreateObjectSet<Employee>("Employees")); }
        }
        private ObjectSet<Employee> _employees;
    
        public ObjectSet<InvoiceNumber> InvoiceNumbers
        {
            get { return _invoiceNumbers  ?? (_invoiceNumbers = CreateObjectSet<InvoiceNumber>("InvoiceNumbers")); }
        }
        private ObjectSet<InvoiceNumber> _invoiceNumbers;
    
        public ObjectSet<Location> Locations
        {
            get { return _locations  ?? (_locations = CreateObjectSet<Location>("Locations")); }
        }
        private ObjectSet<Location> _locations;
    
        public ObjectSet<PaymentMode> PaymentModes
        {
            get { return _paymentModes  ?? (_paymentModes = CreateObjectSet<PaymentMode>("PaymentModes")); }
        }
        private ObjectSet<PaymentMode> _paymentModes;
    
        public ObjectSet<Product> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Product>("Products")); }
        }
        private ObjectSet<Product> _products;
    
        public ObjectSet<PurchaseDetail> PurchaseDetails
        {
            get { return _purchaseDetails  ?? (_purchaseDetails = CreateObjectSet<PurchaseDetail>("PurchaseDetails")); }
        }
        private ObjectSet<PurchaseDetail> _purchaseDetails;
    
        public ObjectSet<Purchase> Purchases
        {
            get { return _purchases  ?? (_purchases = CreateObjectSet<Purchase>("Purchases")); }
        }
        private ObjectSet<Purchase> _purchases;
    
        public ObjectSet<SaleDetail> SaleDetails
        {
            get { return _saleDetails  ?? (_saleDetails = CreateObjectSet<SaleDetail>("SaleDetails")); }
        }
        private ObjectSet<SaleDetail> _saleDetails;
    
        public ObjectSet<Sale> Sales
        {
            get { return _sales  ?? (_sales = CreateObjectSet<Sale>("Sales")); }
        }
        private ObjectSet<Sale> _sales;
    
        public ObjectSet<SaleStatus> SaleStatuses
        {
            get { return _saleStatuses  ?? (_saleStatuses = CreateObjectSet<SaleStatus>("SaleStatuses")); }
        }
        private ObjectSet<SaleStatus> _saleStatuses;
    
        public ObjectSet<SaleType> SaleTypes
        {
            get { return _saleTypes  ?? (_saleTypes = CreateObjectSet<SaleType>("SaleTypes")); }
        }
        private ObjectSet<SaleType> _saleTypes;
    
        public ObjectSet<Supplier> Suppliers
        {
            get { return _suppliers  ?? (_suppliers = CreateObjectSet<Supplier>("Suppliers")); }
        }
        private ObjectSet<Supplier> _suppliers;
    
        public ObjectSet<Tax> Taxes
        {
            get { return _taxes  ?? (_taxes = CreateObjectSet<Tax>("Taxes")); }
        }
        private ObjectSet<Tax> _taxes;
    
        public ObjectSet<ProductLocation> ProductLocations
        {
            get { return _productLocations  ?? (_productLocations = CreateObjectSet<ProductLocation>("ProductLocations")); }
        }
        private ObjectSet<ProductLocation> _productLocations;
    
        public ObjectSet<CardInformation> CardInformations
        {
            get { return _cardInformations  ?? (_cardInformations = CreateObjectSet<CardInformation>("CardInformations")); }
        }
        private ObjectSet<CardInformation> _cardInformations;
    
        public ObjectSet<ProductAdjustment> ProductAdjustments
        {
            get { return _productAdjustments  ?? (_productAdjustments = CreateObjectSet<ProductAdjustment>("ProductAdjustments")); }
        }
        private ObjectSet<ProductAdjustment> _productAdjustments;
    
        public ObjectSet<CompanyDetail> CompanyDetails
        {
            get { return _companyDetails  ?? (_companyDetails = CreateObjectSet<CompanyDetail>("CompanyDetails")); }
        }
        private ObjectSet<CompanyDetail> _companyDetails;
    
        public ObjectSet<Role> Roles
        {
            get { return _roles  ?? (_roles = CreateObjectSet<Role>("Roles")); }
        }
        private ObjectSet<Role> _roles;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<Measurement> Measurements
        {
            get { return _measurements  ?? (_measurements = CreateObjectSet<Measurement>("Measurements")); }
        }
        private ObjectSet<Measurement> _measurements;
    
        public ObjectSet<ErrorLog> ErrorLogs
        {
            get { return _errorLogs  ?? (_errorLogs = CreateObjectSet<ErrorLog>("ErrorLogs")); }
        }
        private ObjectSet<ErrorLog> _errorLogs;
    
        public ObjectSet<StockTranfer> StockTranfers
        {
            get { return _stockTranfers  ?? (_stockTranfers = CreateObjectSet<StockTranfer>("StockTranfers")); }
        }
        private ObjectSet<StockTranfer> _stockTranfers;
    
        public ObjectSet<AccessRight> AccessRights
        {
            get { return _accessRights  ?? (_accessRights = CreateObjectSet<AccessRight>("AccessRights")); }
        }
        private ObjectSet<AccessRight> _accessRights;
    
        public ObjectSet<LabelSetting> LabelSettings
        {
            get { return _labelSettings  ?? (_labelSettings = CreateObjectSet<LabelSetting>("LabelSettings")); }
        }
        private ObjectSet<LabelSetting> _labelSettings;
    
        public ObjectSet<BackupDetail> BackupDetails
        {
            get { return _backupDetails  ?? (_backupDetails = CreateObjectSet<BackupDetail>("BackupDetails")); }
        }
        private ObjectSet<BackupDetail> _backupDetails;
    
        public ObjectSet<CustomerPaymentHistory> CustomerPaymentHistories
        {
            get { return _customerPaymentHistories  ?? (_customerPaymentHistories = CreateObjectSet<CustomerPaymentHistory>("CustomerPaymentHistories")); }
        }
        private ObjectSet<CustomerPaymentHistory> _customerPaymentHistories;

        #endregion
    }
}
