//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace storeManager.Entities
{
    public partial class BackupDetail
    {
        #region Primitive Properties
    
        public virtual int BackupID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> BackupDate
        {
            get;
            set;
        }
    
        public virtual string BackupFolder
        {
            get;
            set;
        }
    
        public virtual string StartTime
        {
            get;
            set;
        }
    
        public virtual string EndTime
        {
            get;
            set;
        }
    
        public virtual string Comments
        {
            get;
            set;
        }
    
        public virtual short UserID
        {
            get;
            set;
        }

        #endregion
    }
}
