//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace storeManager.Entities
{
    public partial class Company
    {
        #region Primitive Properties
    
        public virtual string CompanyNum
        {
            get;
            set;
        }
    
        public virtual string CompanyName
        {
            get;
            set;
        }
    
        public virtual string Address1
        {
            get;
            set;
        }
    
        public virtual string Address2
        {
            get;
            set;
        }
    
        public virtual string Address3
        {
            get;
            set;
        }
    
        public virtual string PhoneLine1
        {
            get;
            set;
        }
    
        public virtual string PhoneLine2
        {
            get;
            set;
        }
    
        public virtual string PhoneLine3
        {
            get;
            set;
        }
    
        public virtual string Motto
        {
            get;
            set;
        }
    
        public virtual byte[] Logo
        {
            get;
            set;
        }
    
        public virtual string Location
        {
            get;
            set;
        }
    
        public virtual string FaxNumber
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual int CompanyID
        {
            get;
            set;
        }
    
        public virtual string Misc
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DefaultLocation
        {
            get;
            set;
        }
    
        public virtual string WebSite
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual string Country
        {
            get;
            set;
        }

        #endregion
    }
}
