//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace storeManager.Entities
{
    public partial class Customer
    {
        #region Primitive Properties
    
        public virtual string CustomerNum
        {
            get;
            set;
        }
    
        public virtual string Surname
        {
            get;
            set;
        }
    
        public virtual string OtherNames
        {
            get;
            set;
        }
    
        public virtual string Sex
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CustomerTypeID
        {
            get;
            set;
        }
    
        public virtual string PhoneNumber1
        {
            get;
            set;
        }
    
        public virtual string PhoneNumber2
        {
            get;
            set;
        }
    
        public virtual string PhoneNumber3
        {
            get;
            set;
        }
    
        public virtual string EmailAddress
        {
            get;
            set;
        }
    
        public virtual string Website
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Discount
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> CreditLimit
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateAdded
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsActive
        {
            get;
            set;
        }
    
        public virtual string CustomerName
        {
            get;
            set;
        }
    
        public virtual string ContactPerson
        {
            get;
            set;
        }
    
        public virtual string PostalAddress
        {
            get;
            set;
        }
    
        public virtual string LocationAdress
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CustomerSince
        {
            get;
            set;
        }
    
        public virtual string Salutation
        {
            get;
            set;
        }
    
        public virtual string Country
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual int CustomerID
        {
            get;
            set;
        }

        #endregion
    }
}
