//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace storeManager.Entities
{
    public partial class LabelSetting
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ListStart
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ListEnd
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LabelLenghth
        {
            get;
            set;
        }
    
        public virtual Nullable<int> QtyToPrint
        {
            get;
            set;
        }
    
        public virtual string BarcodeType
        {
            get;
            set;
        }
    
        public virtual string BorderType
        {
            get;
            set;
        }
    
        public virtual string FontFamily
        {
            get;
            set;
        }
    
        public virtual string ForeColor
        {
            get;
            set;
        }
    
        public virtual Nullable<int> BarHeight
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FontSize
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ShowTest
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ShowBorder
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ShowCheckSum
        {
            get;
            set;
        }

        #endregion
    }
}
