//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace storeManager.Entities
{
    public partial class Location
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsDefault
        {
            get;
            set;
        }
    
        public virtual string Comment
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<ProductLocation> ProductLocations
        {
            get
            {
                if (_productLocations == null)
                {
                    var newCollection = new FixupCollection<ProductLocation>();
                    newCollection.CollectionChanged += FixupProductLocations;
                    _productLocations = newCollection;
                }
                return _productLocations;
            }
            set
            {
                if (!ReferenceEquals(_productLocations, value))
                {
                    var previousValue = _productLocations as FixupCollection<ProductLocation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProductLocations;
                    }
                    _productLocations = value;
                    var newValue = value as FixupCollection<ProductLocation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProductLocations;
                    }
                }
            }
        }
        private ICollection<ProductLocation> _productLocations;

        #endregion
        #region Association Fixup
    
        private void FixupProductLocations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProductLocation item in e.NewItems)
                {
                    item.Location = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductLocation item in e.OldItems)
                {
                    if (ReferenceEquals(item.Location, this))
                    {
                        item.Location = null;
                    }
                }
            }
        }

        #endregion
    }
}
