//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace storeManager.Entities
{
    public partial class ProductAdjustment
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int ProductID
        {
            get;
            set;
        }
    
        public virtual int LocationID
        {
            get;
            set;
        }
    
        public virtual int ProductLocationID
        {
            get;
            set;
        }
    
        public virtual int CurrentQty
        {
            get;
            set;
        }
    
        public virtual int NewQty
        {
            get;
            set;
        }
    
        public virtual int Difference
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AdjustmentDate
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }
    
        public virtual Nullable<int> EmployeeID
        {
            get;
            set;
        }

        #endregion
    }
}
