//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace storeManager.Entities
{
    public partial class Purchase
    {
        #region Primitive Properties
    
        public virtual string InvoiceNumber
        {
            get;
            set;
        }
    
        public virtual string SupplierID
        {
            get;
            set;
        }
    
        public virtual decimal PurchaseAmount
        {
            get;
            set;
        }
    
        public virtual System.DateTime PurchaseDate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> AmountPaid
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Balance
        {
            get;
            set;
        }
    
        public virtual Nullable<int> StoreID
        {
            get;
            set;
        }
    
        public virtual string PurchaseType
        {
            get;
            set;
        }
    
        public virtual string EmployeeID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PurchasetypeID
        {
            get;
            set;
        }
    
        public virtual string DetailedAccountID
        {
            get;
            set;
        }
    
        public virtual string BillState
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Discount
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Tax
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PromisedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DateClosed
        {
            get;
            set;
        }
    
        public virtual string PurchaseOrderNo
        {
            get;
            set;
        }

        #endregion
    }
}
