//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace storeManager.Entities
{
    public partial class SaleDetail
    {
        #region Primitive Properties
    
        public virtual string InvoiceNumber
        {
            get;
            set;
        }
    
        public virtual decimal UnitPrice
        {
            get;
            set;
        }
    
        public virtual int Quantity
        {
            get;
            set;
        }
    
        public virtual int SalesDetailsID
        {
            get;
            set;
        }
    
        public virtual string ProductID
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Discount
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Tax
        {
            get;
            set;
        }
    
        public virtual int SaleID
        {
            get { return _saleID; }
            set
            {
                if (_saleID != value)
                {
                    if (Sale != null && Sale.SaleID != value)
                    {
                        Sale = null;
                    }
                    _saleID = value;
                }
            }
        }
        private int _saleID;
    
        public virtual Nullable<decimal> LineTotal
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LocationID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Sale Sale
        {
            get { return _sale; }
            set
            {
                if (!ReferenceEquals(_sale, value))
                {
                    var previousValue = _sale;
                    _sale = value;
                    FixupSale(previousValue);
                }
            }
        }
        private Sale _sale;

        #endregion
        #region Association Fixup
    
        private void FixupSale(Sale previousValue)
        {
            if (previousValue != null && previousValue.SaleDetails.Contains(this))
            {
                previousValue.SaleDetails.Remove(this);
            }
    
            if (Sale != null)
            {
                if (!Sale.SaleDetails.Contains(this))
                {
                    Sale.SaleDetails.Add(this);
                }
                if (SaleID != Sale.SaleID)
                {
                    SaleID = Sale.SaleID;
                }
            }
        }

        #endregion
    }
}
