//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace storeManager.Entities
{
    public partial class User
    {
        #region Primitive Properties
    
        public virtual int UserID
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual string UserPassword
        {
            get;
            set;
        }
    
        public virtual Nullable<int> EmployeeID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DateCreated
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastLogInDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> RoleID
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Active
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsAdmin
        {
            get;
            set;
        }

        #endregion
    }
}
